### ISSUE TITLE
If no config is added, indexer crash

### ISSUE THREAD

**Issue by WouterSteen** [elgentos/magento2-elasticsuite-prismic-search#11]
Call to private method Elgentos\PrismicIO\Renderer\Page::createPage() from context 'Elgentos\ElasticsuitePrismicSearch\Model\ItemProvider\PrismicDocuments'

**Comment by peterjaap** [comment]
I need a bit more context. Which file, which config?

**Comment by WouterSteen** [comment]
If you run the indexer. After the module is installed.

**Comment by peterjaap** [comment]
I think you may need to run `composer install` or `composer update` since that has already been changed in 1.9.1 of the PrismicIO plugin; https://github.com/elgentos/magento2-prismicio/commit/c494c0187bd2b5e516b2f85803f49603f84556d1

**Comment by peterjaap** [comment]
I've updated the composer.json of this module accordingly; https://github.com/elgentos/magento2-elasticsuite-prismic-search/commit/fd6bf859e22101b2ff761c7f6f406d8ccd8a19e6
